sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t mecanthe/docker-react-app -f Dockerfile.dev

script:
    - docker run -e CI=true mecanthe/docker-react-app npm run test --
after_sucess:
  - echo "Test success"